endpoints:
  - method: "GET"
    url: "/accounts"
    response:
      code: 200
      headers:
        "Content-Type": "application/json"
      body: >
        {
          "id":"1",
          "name":"Gopher"
        }
  - method: "POST"
    url: "/accounts"
    response:
      code: 201
      headers:
        "Content-Type": "application/json"
      body: >
        {
          "id":"1",
          "name":"Gopher"
        }